Repository vuejs/vuex, pull requests merged in 2020-11, with the labels that each got.

#1868 Include mutations in the Vuex 4.x example
  docs/guide/README.md
Labels: docs

#1880 (Add pt-br language) Vuex 4
  docs/.vitepress/config.js
  docs/ptbr/api/index.md
  docs/ptbr/guide/actions.md
  docs/ptbr/guide/composition-api.md
  docs/ptbr/guide/forms.md
  docs/ptbr/guide/getters.md
  docs/ptbr/guide/hot-reload.md
  docs/ptbr/guide/index.md
  docs/ptbr/guide/migrating-to-4-0-from-3-x.md
  docs/ptbr/guide/modules.md
  docs/ptbr/guide/mutations.md
  docs/ptbr/guide/plugins.md
  docs/ptbr/guide/state.md
  docs/ptbr/guide/strict.md
  docs/ptbr/guide/structure.md
  docs/ptbr/guide/testing.md
  docs/ptbr/guide/typescript-support.md
  docs/ptbr/index.md
  docs/ptbr/installation.md
  docs/public/_redirects
Labels: 4.0, documentation

#1872 Add Node.js esm entry point
  package.json
  scripts/build.js
  src/index.mjs
  test/esm/esm-import.mjs
  test/esm/esm-test.js
Labels: build, enhancement

#1882 (docs ptBR fixes 4.0)
  docs/ptbr/api/index.md
  docs/ptbr/guide/migrating-to-4-0-from-3-x.md
  docs/ptbr/guide/modules.md
  docs/ptbr/index.md
Labels: 4.0, documentation

#1886 (docs 4.0 ptbr fix)
  docs/ptbr/api/index.md
Labels: 4.0, documentation

#1885 (Some fixes for Vuex 3 ptbr docs)
  docs/.vuepress/config.js
  docs/ptbr/README.md
  docs/ptbr/api/README.md
  docs/ptbr/guide/README.md
  docs/ptbr/guide/actions.md
  docs/ptbr/guide/getters.md
  docs/ptbr/guide/modules.md
  docs/ptbr/guide/mutations.md
  docs/ptbr/guide/plugins.md
  docs/ptbr/guide/state.md
  docs/ptbr/guide/strict.md
  docs/ptbr/guide/structure.md
Labels: 3.0, documentation

#1887 Update index.md
  docs/guide/index.md
Labels: 4.0, documentation

#1884 fix: fix getters stop working when component is destroyed
  docs/guide/getters.md
  src/store.js
Labels: 4.0, bug
