Repository vuejs/vuex, pull requests merged in 2021-01, with the labels that each got.

#1910 fix #1909: single quotes cannot be identified in package.json of the Windows OS
  package.json
Labels: build

#1916 docs(typescript-support): fix .js in comment
  docs/guide/typescript-support.md
Labels: 4.0, documentation

#1908 test: todomvc case failed in windows and some linux os (#1899)
  test/e2e/todomvc.spec.js
Labels: test

#1912 docs: fix broken anchor link
  docs/guide/migrating-to-4-0-from-3-x.md
Labels: documentation

#1907 fix: webpack bundle with 'vuex.esm-bundler.js' (#1906)
  package.json
Labels: build
