Repository vuejs/vuex, pull requests merged in 2021-06, with the labels that each got.

#1986 fix: no getters displayed on root module + better getters inspector
  src/plugins/devtool.js
Labels: 4.0, enhancement

#1990 Docs (pt-br): Update typescript-support.md store.js to store.ts
  docs/ptbr/guide/typescript-support.md
Labels: documentation

#1980 docs(ja): add Japanese docs for vuex 4.0
  docs/.vitepress/config.js
  docs/ja/api/index.md
  docs/ja/guide/actions.md
  docs/ja/guide/composition-api.md
  docs/ja/guide/forms.md
  docs/ja/guide/getters.md
  docs/ja/guide/hot-reload.md
  docs/ja/guide/index.md
  docs/ja/guide/migrating-to-4-0-from-3-x.md
  docs/ja/guide/modules.md
  docs/ja/guide/mutations.md
  docs/ja/guide/plugins.md
  docs/ja/guide/state.md
  docs/ja/guide/strict.md
  docs/ja/guide/structure.md
  docs/ja/guide/testing.md
  docs/ja/guide/typescript-support.md
  docs/ja/index.md
  docs/ja/installation.md
Labels: 4.0, documentation

#1992 fix(devtools): fix __VUE_PROD_DEVTOOLS__ defined in cjs build (#1991)
  rollup.config.js
Labels: 4.0, bug

#2000 update warning version
  docs/guide/getters.md
Labels: 4.0, documentation
