Repository vuejs/vuex, pull requests merged in 2021-10, with the labels that each got.

#1883 fix: fix getters being destroyed on component destroy (#1878)
  package.json
  src/store-util.js
  src/store.js
  test/helpers.js
  test/unit/modules.spec.js
  yarn.lock
Labels: bug, 4.0

#2048 Fix deprecated warning in package.json export module (fix #2047)
  package.json
Labels: enhancement, 3.0

#2043 docs: Change `funciton` to `method`
  docs/guide/composition-api.md
Labels: documentation, 4.0
